### ISSUE TITLE
About the mask data

### ISSUE THREAD

**Issue by LuckyyySTA** [mcao516/rej-summ#1]
Hello! Thank you for sharing your awesome work~ I am really interested in your work. I notice that there is an argument named `abstention-mask-dir` in your script. Could you please release the mask data? Thanks a lot!

**Comment by mcao516** [comment]
Hello, thank you for your interest in our work. Here is the data for XSum:
[https://drive.google.com/file/d/1zZrhxOAgD2qc4dMrFpXrYxHm-XC85yYY/view?usp=sharing](url)

I will upload the pre-processing scripts soon.

**Comment by LuckyyySTA** [comment]
Thanks a lot!
